name: ESP32 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ESP-IDF
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv git wget flex bison gperf cmake ninja-build ccache libffi-dev libssl-dev dfu-util
          git clone --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          ./install.sh

      - name: Load ESP-IDF environment
        run: |
          source $HOME/esp-idf/export.sh
          echo "ESP-IDF environment loaded"

      - name: Configure and Build
        run: |
          source $HOME/esp-idf/export.sh
          idf.py set-target esp32
          idf.py build

      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: esp32-firmware
          path: build/*.bin
